/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ShopifyRouteImport } from './routes/shopify'
import { Route as SelarRouteImport } from './routes/selar'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PaystackRouteImport } from './routes/paystack'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as EliteCheckoutRouteImport } from './routes/elite-checkout'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentEngineRouteImport } from './routes/_authenticated/content-engine'
import { Route as AuthenticatedCandyRouteImport } from './routes/_authenticated/candy'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicWebhookSelftestRouteImport } from './routes/api/public/_webhook-selftest'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyRoute = ShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const SelarRoute = SelarRouteImport.update({
  id: '/selar',
  path: '/selar',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PaystackRoute = PaystackRouteImport.update({
  id: '/paystack',
  path: '/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteCheckoutRoute = EliteCheckoutRouteImport.update({
  id: '/elite-checkout',
  path: '/elite-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentEngineRoute =
  AuthenticatedContentEngineRouteImport.update({
    id: '/content-engine',
    path: '/content-engine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandyRoute = AuthenticatedCandyRouteImport.update({
  id: '/candy',
  path: '/candy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookSelftestRoute =
  ApiPublicWebhookSelftestRouteImport.update({
    id: '/api/public/_webhook-selftest',
    path: '/api/public',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/crypto': typeof CryptoRoute
  '/elite-checkout': typeof EliteCheckoutRoute
  '/hubs': typeof HubsRoute
  '/login': typeof LoginRoute
  '/paystack': typeof PaystackRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/selar': typeof SelarRoute
  '/shopify': typeof ShopifyRoute
  '/success': typeof SuccessRoute
  '/candy': typeof AuthenticatedCandyRoute
  '/content-engine': typeof AuthenticatedContentEngineRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public': typeof ApiPublicWebhookSelftestRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/crypto': typeof CryptoRoute
  '/elite-checkout': typeof EliteCheckoutRoute
  '/hubs': typeof HubsRoute
  '/login': typeof LoginRoute
  '/paystack': typeof PaystackRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/selar': typeof SelarRoute
  '/shopify': typeof ShopifyRoute
  '/success': typeof SuccessRoute
  '/candy': typeof AuthenticatedCandyRoute
  '/content-engine': typeof AuthenticatedContentEngineRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public': typeof ApiPublicWebhookSelftestRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/checkout': typeof CheckoutRoute
  '/crypto': typeof CryptoRoute
  '/elite-checkout': typeof EliteCheckoutRoute
  '/hubs': typeof HubsRoute
  '/login': typeof LoginRoute
  '/paystack': typeof PaystackRoute
  '/products': typeof ProductsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/selar': typeof SelarRoute
  '/shopify': typeof ShopifyRoute
  '/success': typeof SuccessRoute
  '/_authenticated/candy': typeof AuthenticatedCandyRoute
  '/_authenticated/content-engine': typeof AuthenticatedContentEngineRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/_webhook-selftest': typeof ApiPublicWebhookSelftestRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bundles'
    | '/checkout'
    | '/crypto'
    | '/elite-checkout'
    | '/hubs'
    | '/login'
    | '/paystack'
    | '/products'
    | '/quiz'
    | '/selar'
    | '/shopify'
    | '/success'
    | '/candy'
    | '/content-engine'
    | '/dashboard'
    | '/gallery'
    | '/products/$slug'
    | '/api/public'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bundles'
    | '/checkout'
    | '/crypto'
    | '/elite-checkout'
    | '/hubs'
    | '/login'
    | '/paystack'
    | '/products'
    | '/quiz'
    | '/selar'
    | '/shopify'
    | '/success'
    | '/candy'
    | '/content-engine'
    | '/dashboard'
    | '/gallery'
    | '/products/$slug'
    | '/api/public'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/bundles'
    | '/checkout'
    | '/crypto'
    | '/elite-checkout'
    | '/hubs'
    | '/login'
    | '/paystack'
    | '/products'
    | '/quiz'
    | '/selar'
    | '/shopify'
    | '/success'
    | '/_authenticated/candy'
    | '/_authenticated/content-engine'
    | '/_authenticated/dashboard'
    | '/_authenticated/gallery'
    | '/products/$slug'
    | '/api/public/_webhook-selftest'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BundlesRoute: typeof BundlesRoute
  CheckoutRoute: typeof CheckoutRoute
  CryptoRoute: typeof CryptoRoute
  EliteCheckoutRoute: typeof EliteCheckoutRoute
  HubsRoute: typeof HubsRoute
  LoginRoute: typeof LoginRoute
  PaystackRoute: typeof PaystackRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuizRoute: typeof QuizRoute
  SelarRoute: typeof SelarRoute
  ShopifyRoute: typeof ShopifyRoute
  SuccessRoute: typeof SuccessRoute
  ApiPublicWebhookSelftestRoute: typeof ApiPublicWebhookSelftestRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify': {
      id: '/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof ShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selar': {
      id: '/selar'
      path: '/selar'
      fullPath: '/selar'
      preLoaderRoute: typeof SelarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paystack': {
      id: '/paystack'
      path: '/paystack'
      fullPath: '/paystack'
      preLoaderRoute: typeof PaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite-checkout': {
      id: '/elite-checkout'
      path: '/elite-checkout'
      fullPath: '/elite-checkout'
      preLoaderRoute: typeof EliteCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-engine': {
      id: '/_authenticated/content-engine'
      path: '/content-engine'
      fullPath: '/content-engine'
      preLoaderRoute: typeof AuthenticatedContentEngineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candy': {
      id: '/_authenticated/candy'
      path: '/candy'
      fullPath: '/candy'
      preLoaderRoute: typeof AuthenticatedCandyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/_webhook-selftest': {
      id: '/api/public/_webhook-selftest'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicWebhookSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCandyRoute: typeof AuthenticatedCandyRoute
  AuthenticatedContentEngineRoute: typeof AuthenticatedContentEngineRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCandyRoute: AuthenticatedCandyRoute,
  AuthenticatedContentEngineRoute: AuthenticatedContentEngineRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BundlesRoute: BundlesRoute,
  CheckoutRoute: CheckoutRoute,
  CryptoRoute: CryptoRoute,
  EliteCheckoutRoute: EliteCheckoutRoute,
  HubsRoute: HubsRoute,
  LoginRoute: LoginRoute,
  PaystackRoute: PaystackRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuizRoute: QuizRoute,
  SelarRoute: SelarRoute,
  ShopifyRoute: ShopifyRoute,
  SuccessRoute: SuccessRoute,
  ApiPublicWebhookSelftestRoute: ApiPublicWebhookSelftestRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
